INSERT INTO PENDING_PARTICIPANT_FUND(AVG_FUNDNAV,FUNDID,FUND_NAME,FUND_UNITS_HELD,PARTICIPANT_HOLDING_PERCENTAGE,PARTICIPANTID,PARTICIPANT_NAME,PLANID,PREVIOUS_FUNDEXCHANGE_DATE,PROCESSED,WITHDRAWAL_STATUS,WITH_DRAWAL_UNITS)
VALUES
(1000,1,'LARGE CAP',100,50,101,'CUSTOMER1',1,now(),'N','PARTIAL',0);

INSERT INTO PENDING_PARTICIPANT_FUND(AVG_FUNDNAV,FUNDID,FUND_NAME,FUND_UNITS_HELD,PARTICIPANT_HOLDING_PERCENTAGE,PARTICIPANTID,PARTICIPANT_NAME,PLANID,PREVIOUS_FUNDEXCHANGE_DATE,PROCESSED,WITHDRAWAL_STATUS,WITH_DRAWAL_UNITS)
VALUES
(500,2,'SMALL CAP',100,50,102,'CUSTOMER2',1,now(),'N','FULL',0);

INSERT INTO PENDING_PARTICIPANT_FUND(AVG_FUNDNAV,FUNDID,FUND_NAME,FUND_UNITS_HELD,PARTICIPANT_HOLDING_PERCENTAGE,PARTICIPANTID,PARTICIPANT_NAME,PLANID,PREVIOUS_FUNDEXCHANGE_DATE,PROCESSED,WITHDRAWAL_STATUS,WITH_DRAWAL_UNITS)
VALUES
(1000,1,'LARGE CAP',100,50,103,'CUSTOMER3',1,now(),'N','PARTIAL',0);

INSERT INTO PENDING_PARTICIPANT_FUND(AVG_FUNDNAV,FUNDID,FUND_NAME,FUND_UNITS_HELD,PARTICIPANT_HOLDING_PERCENTAGE,PARTICIPANTID,PARTICIPANT_NAME,PLANID,PREVIOUS_FUNDEXCHANGE_DATE,PROCESSED,WITHDRAWAL_STATUS,WITH_DRAWAL_UNITS)
VALUES
(500,1,'SMALL CAP',100,50,104,'CUSTOMER4',1,now(),'N','FULL',0);

INSERT INTO PENDING_PARTICIPANT_FUND(AVG_FUNDNAV,FUNDID,FUND_NAME,FUND_UNITS_HELD,PARTICIPANT_HOLDING_PERCENTAGE,PARTICIPANTID,PARTICIPANT_NAME,PLANID,PREVIOUS_FUNDEXCHANGE_DATE,PROCESSED,REFERENCE_TRANSACTIONID,WITHDRAWAL_STATUS,WITH_DRAWAL_UNITS)
VALUES
(500,1,'SMALL CAP',100,50,104,'CUSTOMER4',1,now(),'N',4,'FULL',0);












INSERT INTO PARTICIPANT_FUND(FUNDID,PARTICIPANTID,PLANID,ACTIVE,AVG_FUNDNAV,FUND_NAME,FUND_UNITS_HELD,PARTICIPANT_HOLDING_PERCENTAGE,PARTICIPANT_NAME,PREVIOUS_FUNDEXCHANGE_DATE)
VALUES
(1,101,1,'Y',1000,'LARGE CAP',100,50,'CUSTOMER1',now());

INSERT INTO PARTICIPANT_FUND(FUNDID,PARTICIPANTID,PLANID,ACTIVE,AVG_FUNDNAV,FUND_NAME,FUND_UNITS_HELD,PARTICIPANT_HOLDING_PERCENTAGE,PARTICIPANT_NAME,PREVIOUS_FUNDEXCHANGE_DATE)
VALUES
(2,102,1,'Y',1000,'SMALL CAP',100,50,'CUSTOMER2',now());





